include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unawaited_futures: true
